# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8258219c7579312f5aca3bf2a3b0b233cd15f864de512b2f7ca798abe152d6e6e86d609a65b8db979b4a3fd4f77c06f7978e288e4726580fe825cf087982e8c

test:
  secret_key_base: 8b3530384f0e41b7c545cdd214e180b47ff0238d6f160aa10f41937c2de23aa392b72f6bc55a2d3a4a9c840f707482c3c1929b06046fdc2fac64e3197e52ac84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
